/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.Vista.GUI;

/**
 *
 * @author sebas
 */
public class Puntuacion extends javax.swing.JFrame {
     

    /**
     * Creates new form Puntuacion2
     */
    public Puntuacion(String jugador1) {
        initComponents();
        this.nombreJugador1.setText(jugador1);
    }
    
    public Puntuacion (String jugador1, String jugador2){
        initComponents();
        this.nombreJugador1.setText(jugador1);
        this.nombreJugador2.setText(jugador2);
    }
    
    public Puntuacion (String jugador1, String jugador2, String jugador3){
        initComponents();
        this.nombreJugador1.setText(jugador1);
        this.nombreJugador2.setText(jugador2);
        this.nombreJugador3.setText(jugador3);
    }
    
    public Puntuacion (String jugador1, String jugador2, String jugador3, String jugador4){
        initComponents();
        this.nombreJugador1.setText(jugador1);
        this.nombreJugador2.setText(jugador2);
        this.nombreJugador3.setText(jugador3);
        this.nombreJugador4.setText(jugador4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreJugador1 = new javax.swing.JLabel();
        nombreJugador2 = new javax.swing.JLabel();
        nombreJugador3 = new javax.swing.JLabel();
        nombreJugador4 = new javax.swing.JLabel();
        puntJ1 = new javax.swing.JLabel();
        puntJ2 = new javax.swing.JLabel();
        puntJ3 = new javax.swing.JLabel();
        puntJ4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreJugador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puntJ1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreJugador2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puntJ2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreJugador3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puntJ3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nombreJugador4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(puntJ4)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJugador1)
                    .addComponent(puntJ1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJugador2)
                    .addComponent(puntJ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJugador3)
                    .addComponent(puntJ3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreJugador4)
                    .addComponent(puntJ4))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JLabel puntJ1;
    private javax.swing.JLabel puntJ2;
    private javax.swing.JLabel puntJ3;
    private javax.swing.JLabel puntJ4;
    // End of variables declaration//GEN-END:variables
    public void setJugador1Puntuacion(String puntos){
        this.
        puntJ1.setText(puntos);
    }
    
    public void setJugador2Puntuacion(String puntos){
        puntJ2.setText(puntos);
    }
    
    public void setJugador3Puntuacion(String puntos){
        puntJ3.setText(puntos);
    }
    
    public void setJugador4Puntuacion(String puntos){
        puntJ4.setText(puntos);
    }
}


