/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente.GUI;


import javafx.beans.Observable;

/**
 *
 * @author Yoshiki
 */
public class Puntuacion extends javax.swing.JPanel{

    /**
     * Creates new form Puntuacion
     */
    public Puntuacion(String jugador1) {
        initComponents();
        this.nombreJugador1.setText(jugador1);
    }
    
    public Puntuacion (String jugador1, String jugador2){
        initComponents();
        this.nombreJugador1.setText(jugador1);
        this.nombreJugador2.setText(jugador2);
    }
    
    public Puntuacion (String jugador1, String jugador2, String jugador3){
        initComponents();
        this.nombreJugador1.setText(jugador1);
        this.nombreJugador2.setText(jugador2);
        this.nombreJugador3.setText(jugador3);
    }
    
    public Puntuacion (String jugador1, String jugador2, String jugador3, String jugador4){
        initComponents();
        this.nombreJugador1.setText(jugador1);
        this.nombreJugador2.setText(jugador2);
        this.nombreJugador3.setText(jugador3);
        this.nombreJugador4.setText(jugador4);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreJugador1 = new javax.swing.JLabel();
        puntJ1 = new javax.swing.JLabel();
        nombreJugador2 = new javax.swing.JLabel();
        puntJ2 = new javax.swing.JLabel();
        nombreJugador3 = new javax.swing.JLabel();
        puntJ3 = new javax.swing.JLabel();
        nombreJugador4 = new javax.swing.JLabel();
        puntJ4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.GridLayout(4, 2));
        add(nombreJugador1);
        nombreJugador1.getAccessibleContext().setAccessibleName("nombreJugador1");

        add(puntJ1);
        puntJ1.getAccessibleContext().setAccessibleName("puntJ1");

        add(nombreJugador2);
        nombreJugador2.getAccessibleContext().setAccessibleName("nombreJugador2");

        add(puntJ2);
        puntJ2.getAccessibleContext().setAccessibleName("puntJ2");

        add(nombreJugador3);
        nombreJugador3.getAccessibleContext().setAccessibleName("nombreJugador3");

        add(puntJ3);
        puntJ3.getAccessibleContext().setAccessibleName("puntJ3");

        add(nombreJugador4);
        nombreJugador4.getAccessibleContext().setAccessibleName("nombreJugador4");

        add(puntJ4);
        puntJ4.getAccessibleContext().setAccessibleName("puntJ4");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nombreJugador1;
    private javax.swing.JLabel nombreJugador2;
    private javax.swing.JLabel nombreJugador3;
    private javax.swing.JLabel nombreJugador4;
    private javax.swing.JLabel puntJ1;
    private javax.swing.JLabel puntJ2;
    private javax.swing.JLabel puntJ3;
    private javax.swing.JLabel puntJ4;
    // End of variables declaration//GEN-END:variables

    public void setJugador1Puntuacion(String puntos){
        puntJ1.setText(puntos);
    }
    
    public void setJugador2Puntuacion(String puntos){
        puntJ1.setText(puntos);
    }
    
    public void setJugador3Puntuacion(String puntos){
        puntJ1.setText(puntos);
    }
    
    public void setJugador4Puntuacion(String puntos){
        puntJ1.setText(puntos);
    }
}
